plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
      spec: "@yarnpkg/plugin-typescript"
    - path: .yarn/plugins/@yarnpkg/plugin-pin-deps.cjs
      spec: "https://raw.githubusercontent.com/splitgraph/yarn-plugin-pin-deps/main/packages/plugin-pin-deps/bundles/%40yarnpkg/plugin-pin-deps.js"

pnpFallbackMode: none

yarnPath: .yarn/releases/yarn-3.6.1.cjs
